<a href="https://colab.research.google.com/github/Chris-11-star/Basic-Sql-Statmentss/blob/main/Untitled0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
from google.colab import files
files=files.upload()

Saving database.sqlite to database.sqlite

In [4]:
import sqlite3
database='database.sqlite'
conn=sqlite3.connect(database)
print("opened data sucessfully")

opened data sucessfully

In [9]:
import pandas as pd
query="SELECT * FROM sqlite_master WHERE type='table'"
table=pd.read_sql_query(query,conn)
print(table)

     type             name         tbl_name  rootpage  \
0   table           Player           Player         2
1   table       Extra_Runs       Extra_Runs         3
2   table   Batsman_Scored   Batsman_Scored         7
3   table    Batting_Style    Batting_Style        10
4   table    Bowling_Style    Bowling_Style        11
5   table          Country          Country        12
6   table           Season           Season        14
7   table             City             City        15
8   table          Outcome          Outcome        16
9   table           Win_By           Win_By        17
10  table     Wicket_Taken     Wicket_Taken        18
11  table            Venue            Venue        21
12  table       Extra_Type       Extra_Type        23
13  table         Out_Type         Out_Type        24
14  table    Toss_Decision    Toss_Decision        25
15  table           Umpire           Umpire        26
16  table             Team             Team        27
17  table     Ball_by_Ball     Ball_by_Ball        28
18  table      sysdiagrams      sysdiagrams        31
19  table  sqlite_sequence  sqlite_sequence        32
20  table            Match            Match        34
21  table            Rolee            Rolee        36
22  table     Player_Match     Player_Match        37

                                                  sql
0   CREATE TABLE [Player] (\n\t[Player_Id]\tintege...
1   CREATE TABLE [Extra_Runs] (\n\t[Match_Id]\tint...
2   CREATE TABLE [Batsman_Scored] (\n\t[Match_Id]\...
3   CREATE TABLE [Batting_Style] (\n\t[Batting_Id]...
4   CREATE TABLE [Bowling_Style] (\n\t[Bowling_Id]...
5   CREATE TABLE [Country] (\n\t[Country_Id]\tinte...
6   CREATE TABLE [Season] (\n\t[Season_Id]\tintege...
7   CREATE TABLE [City] (\n\t[City_Id]\tinteger NO...
8   CREATE TABLE [Outcome] (\n\t[Outcome_Id]\tinte...
9   CREATE TABLE [Win_By] (\n\t[Win_Id]\tinteger N...
10  CREATE TABLE [Wicket_Taken] (\n\t[Match_Id]\ti...
11  CREATE TABLE [Venue] (\n\t[Venue_Id]\tinteger ...
12  CREATE TABLE [Extra_Type] (\n\t[Extra_Id]\tint...
13  CREATE TABLE [Out_Type] (\n\t[Out_Id]\tinteger...
14  CREATE TABLE [Toss_Decision] (\n\t[Toss_Id]\ti...
15  CREATE TABLE [Umpire] (\n\t[Umpire_Id]\tintege...
16  CREATE TABLE [Team] (\n\t[Team_Id]\tinteger NO...
17  CREATE TABLE [Ball_by_Ball] (\n\t[Match_Id]\ti...
18  CREATE TABLE [sysdiagrams] (\n\t[name]\tnvarch...
19             CREATE TABLE sqlite_sequence(name,seq)
20  CREATE TABLE [Match] (\n\t[Match_Id]\tinteger ...
21  CREATE TABLE [Rolee] (\n\t[Role_Id]\tinteger N...
22  CREATE TABLE [Player_Match] (\n\t[Match_Id]\ti...

In [10]:
query="SELECT * FROM Match"
match=pd.read_sql_query(query,conn)
match.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 577 entries, 0 to 576
Data columns (total 13 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Match_Id          577 non-null    int64
 1   Team_1            577 non-null    int64
 2   Team_2            577 non-null    int64
 3   Match_Date        577 non-null    object
 4   Season_Id         577 non-null    int64
 5   Venue_Id          577 non-null    int64
 6   Toss_Winner       577 non-null    int64
 7   Toss_Decide       577 non-null    int64
 8   Win_Type          577 non-null    int64
 9   Win_Margin        568 non-null    float64
 10  Outcome_type      577 non-null    int64
 11  Match_Winner      574 non-null    float64
 12  Man_of_the_Match  574 non-null    float64
dtypes: float64(3), int64(9), object(1)
memory usage: 58.7+ KB

In [11]:
match.head(10)

,Match_Id,Team_1,Team_2,Match_Date,Season_Id,Venue_Id,Toss_Winner,Toss_Decide,Win_Type,Win_Margin,Outcome_type,Match_Winner,Man_of_the_Match
0,335987,2,1,2008-04-18 00:00:00,1,1,2,1,1,140.0,1,1.0,2.0
1,335988,4,3,2008-04-19 00:00:00,1,2,3,2,1,33.0,1,3.0,19.0
2,335989,6,5,2008-04-19 00:00:00,1,3,5,2,2,9.0,1,6.0,90.0
3,335990,7,2,2008-04-20 00:00:00,1,4,7,2,2,5.0,1,2.0,11.0
4,335991,1,8,2008-04-20 00:00:00,1,5,8,2,2,5.0,1,1.0,4.0
5,335992,5,4,2008-04-21 00:00:00,1,6,4,2,2,6.0,1,5.0,32.0
6,335993,8,6,2008-04-22 00:00:00,1,7,8,2,2,9.0,1,6.0,41.0
7,335994,3,7,2008-04-23 00:00:00,1,8,7,1,1,6.0,1,3.0,18.0
8,335995,8,5,2008-04-24 00:00:00,1,7,5,1,2,3.0,1,5.0,31.0
9,335996,4,7,2008-04-25 00:00:00,1,2,7,1,1,66.0,1,4.0,26.0

In [13]:
query="SELECT * FROM Team"
team=pd.read_sql_query(query,conn)
print(team)

    Team_Id                    Team_Name
0         1        Kolkata Knight Riders
1         2  Royal Challengers Bangalore
2         3          Chennai Super Kings
3         4              Kings XI Punjab
4         5             Rajasthan Royals
5         6             Delhi Daredevils
6         7               Mumbai Indians
7         8              Deccan Chargers
8         9         Kochi Tuskers Kerala
9        10                Pune Warriors
10       11          Sunrisers Hyderabad
11       12      Rising Pune Supergiants
12       13                Gujarat Lions

In [14]:
query="SELECT * FROM Match WHERE Match_Winner ==7"
MI_Win=pd.read_sql_query(query,conn)
print(MI_Win)

    Match_Id  Team_1  Team_2           Match_Date  Season_Id  Venue_Id  \
0     336002       1       7  2008-04-29 00:00:00          1         5
1     336009       7       6  2008-05-04 00:00:00          1         9
2     336013       7       5  2008-05-07 00:00:00          1         9
3     336017       2       7  2008-05-28 00:00:00          1         1
4     336023       7       3  2008-05-14 00:00:00          1         4
..       ...     ...     ...                  ...        ...       ...
75    980946       4       7  2016-04-25 00:00:00          9        33
76    980952       7       1  2016-04-28 00:00:00          9         4
77    980962      12       7  2016-05-01 00:00:00          9        32
78    980986       2       7  2016-05-11 00:00:00          9         1
79    980998       7       6  2016-05-15 00:00:00          9        25

    Toss_Winner  Toss_Decide  Win_Type  Win_Margin  Outcome_type  \
0             1            2         2           7             1
1             6            1         1          29             1
2             7            1         2           7             1
3             7            1         2           9             1
4             7            1         2           9             1
..          ...          ...       ...         ...           ...
75            4            1         1          25             1
76            7            1         2           6             1
77            7            1         2           8             1
78            7            1         2           6             1
79            6            1         1          80             1

    Match_Winner  Man_of_the_Match
0              7                44
1              7                49
2              7                73
3              7               149
4              7                44
..           ...               ...
75             7                17
76             7                57
77             7                57
78             7               413
79             7               413

[80 rows x 13 columns]

In [15]:
query="SELECT * FROM Match WHERE Match_Winner ==7 and Season_Id IN (8,9)"
MI_Win_8_9=pd.read_sql_query(query,conn)
print(MI_Win_8_9)

    Match_Id  Team_1  Team_2           Match_Date  Season_Id  Venue_Id  \
0     829742       2       7  2015-04-19 00:00:00          8         1
1     829756       7      11  2015-04-25 00:00:00          8         4
2     829774       7       5  2015-05-01 00:00:00          8         4
3     829780       4       7  2015-05-03 00:00:00          8         2
4     829788       7       6  2015-05-05 00:00:00          8         4
5     829794       3       7  2015-05-08 00:00:00          8         8
6     829810       7       1  2015-05-14 00:00:00          8         4
7     829820      11       7  2015-05-17 00:00:00          8         7
8     829822       3       7  2015-05-19 00:00:00          8         4
9     829828       7       3  2015-05-24 00:00:00          8         5
10    980914       1       7  2016-04-13 00:00:00          9         5
11    980932       7       2  2016-04-20 00:00:00          9         4
12    980946       4       7  2016-04-25 00:00:00          9        33
13    980952       7       1  2016-04-28 00:00:00          9         4
14    980962      12       7  2016-05-01 00:00:00          9        32
15    980986       2       7  2016-05-11 00:00:00          9         1
16    980998       7       6  2016-05-15 00:00:00          9        25

    Toss_Winner  Toss_Decide  Win_Type  Win_Margin  Outcome_type  \
0             2            1         1          18             1
1             7            2         1          20             1
2             5            1         1           8             1
3             7            2         1          23             1
4             6            2         2           5             1
5             3            2         2           6             1
6             1            1         1           5             1
7            11            2         2           9             1
8             7            2         1          25             1
9             3            1         1          41             1
10            7            1         2           6             1
11            7            1         2           6             1
12            4            1         1          25             1
13            7            1         2           6             1
14            7            1         2           8             1
15            7            1         2           6             1
16            6            1         1          80             1

    Match_Winner  Man_of_the_Match
0              7                50
1              7               194
2              7               208
3              7               383
4              7                50
5              7               400
6              7               400
7              7               403
8              7               221
9              7                57
10             7                57
11             7                57
12             7                17
13             7                57
14             7                57
15             7               413
16             7               413

In [17]:
query="SELECT MIN(win_Margin), MAX(Win_margin) FROM Match"
margin=pd.read_sql_query(query,conn)
margin

   MIN(win_Margin)  MAX(Win_margin)
0                1              144

In [20]:
query="SELECT * FROM Team WHERE Team_name LIKE 'De%'"
team=pd.read_sql_query(query,conn)
team

   Team_Id         Team_Name
0        6  Delhi Daredevils
1        8   Deccan Chargers